

import React, { useState } from "react";


const TermsAndConditions = () => {
    return (
      <div className="terms-and-conditions px-4 py-8">
       
        <p className="mb-4">
          This document is an electronic record in terms of the Information Technology Act, 2000 and
          rules made thereunder as applicable and the amended provisions pertaining to electronic
          records in various statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not require any physical or
          digital signatures.
        </p>
        <p className="mb-4">
          This document is published in accordance with the provisions of Rule 3 (1) of the
          Information Technology (Intermediaries guidelines) Rules, 2011, which require publishing
          the rules and regulations, privacy policy, and user agreement for access or usage of the
          <strong> www.sanctumprop.com</strong> website.
        </p>
        <p className="mb-4">
          Your use of the Sanctum website <strong>www.sanctumprop.com</strong> (hereinafter referred
          to as the "Website") and its related sites, services, and tools is governed by the terms
          and conditions as contained in this Agreement applicable to the Website and for other
          websites of Sanctum Property Management Private Limited and our subsidiaries and
          international affiliates ("User Agreement"). Sanctumprop.com is an internet-based portal
          owned and operated by Sanctum Property Management Private Limited, a company incorporated
          under the Companies Act, 2013, having its registered office at No. 2, Gopal Menon Street,
          Near Doveton Playground, Chennai, Tamil Nadu - 600112.
        </p>
        <p className="mb-4">
          For the purpose of this User Agreement, Registered User/Guest User and wherever the context
          so require "you", "your" shall mean any natural or legal person who is accessing the
          Website, its contents, and using the services offered on or through the Website and has
          agreed to become a member of the Website by providing Registration Data (as defined
          hereinafter) while registering on the Website as Registered User/Guest User using the
          computer systems of the Website and accepted this electronic version/electronic record of
          the User Agreement and has allocated himself/herself a unique identification user name
          ("User ID" and "Password") to become a Registered User or have been identified as a Guest
          User by providing a phone number and email ID.
        </p>
        <p className="mb-4">
          Further, reference to "we", "us", "our" and "Sanctum" shall mean Sanctum Property Management
          Private Limited (Sanctumprop.com) and includes its associates, affiliates, and subsidiaries.
        </p>
        <h3 className="text-xl font-semibold mt-6 mb-4">Amendments</h3>
        <p className="mb-4">
          When you use any of the services provided by us through the Website, including but not
          limited to Reviews, etc., you will be subject to the rules, guidelines, policies, terms,
          and conditions applicable to such service, and they shall be deemed to be incorporated into
          this User Agreement and considered part and parcel of this User Agreement. We reserve the
          right, at our sole discretion, to change, modify, add or remove portions of the User
          Agreement at any time without any prior written notice to you. It is your responsibility to
          review this User Agreement periodically for updates/changes.
        </p>
        <p className="mb-4">
          By accepting this User Agreement, you also accept and agree to be bound by Sanctum’s Rules
          and Policies as provided from time to time in the following hyperlinks:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>
            Sanctumprop.com Terms of Use -{" "}
            <a
              href="https://www.sanctumprop.com/legal-terms"
              className="text-blue-700 underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              www.sanctumprop.com/legal-terms
            </a>
          </li>
          <li>
            Sanctumprop.com Privacy Policy -{" "}
            <a
              href="https://www.sanctumprop.com/legal-privacy"
              className="text-blue-700 underline"
              target="_blank"
              rel="noopener noreferrer"
            >
              www.sanctumprop.com/legal-privacy
            </a>
          </li>
        </ul>
        <h3 className="text-xl font-semibold mt-6 mb-4">Website Security</h3>
        <p className="mb-4">
          You may not violate or attempt to violate the security of the Website. Tampering with any
          portion of the Website, providing untruthful or inaccurate information, misrepresenting
          your identity, or conducting fraudulent activities on the Website, whether or not through
          the use of agents, are prohibited and constitute a breach of these Terms and Conditions of
          Use.
        </p>
        <p className="mb-4">
          Any violations of system or network security, including attempts to intentionally access a
          computer without authorization or exceed your authorized access level, may result in civil
          and criminal charges, including but not limited to charges under applicable laws. Sanctum
          may investigate occurrences that might involve such violations and may involve, and
          cooperate with, law enforcement authorities in prosecuting users who are involved in such
          violations.
        </p>
        <h3 className="text-xl font-semibold mt-6 mb-4">Governing Law</h3>
        <p>
          The User Agreement or the documents incorporated by reference shall be governed and
          construed in accordance with the laws of India. Subject to the clause of Arbitration above,
          all disputes arising under this Agreement between you and Sanctum shall be subject to the
          exclusive jurisdiction of courts at Chennai, Tamil Nadu, India.
        </p>
      </div>
    );
  };



const PrivacyPolicy = () => {
  return (
    <div className="privacy-policy px-4 py-8">
      
      <p className="mb-4">
        In the course of a User/Subscriber using the website{" "}
        <strong>www.sanctumprop.com</strong> ("Website") and the Sanctum Mobile Application ("App")
        or availing the Services and Facilities hereunder, Sanctum Property Management Private
        Limited ("Company") may become privy to the personal information of the user/subscribers,
        including information that is of a confidential nature.
      </p>
      <p className="mb-4">
        This Policy ("Privacy Policy") is an integral part of the Terms of Use as mentioned on the
        Website and App. This Privacy Policy is incorporated into the Terms of Use by reference.
        The words "You" "Your" "User" and "Subscriber" in this Privacy Policy will have the same
        contextual meaning unless defined otherwise.
      </p>
      <p className="mb-4">
        We value the trust you place in us, that's why we insist upon the highest standards for
        secure communication and customer information privacy. Please read the following statement
        to learn about our information gathering and dissemination practices. The Privacy Policy
        specified herein is subject to change at any time without notice. To make sure you are
        aware of any changes, please review this policy periodically.
      </p>
      <p className="mb-4">
        By visiting the website and/or App and/or using the Services you agree to be bound by the
        terms and conditions of this Privacy Policy. If you do not agree, please do not use or
        access Sanctum Website and/or Sanctum App.
      </p>
      <p className="mb-4">
        By mere use of the Website/App, you expressly consent to our use and disclosure of your
        personal and non-personal information in accordance with this Privacy Policy. This Privacy
        Policy is incorporated into and subject to the Terms of Use.
      </p>
      <p className="mb-4">
        The Company has taken all reasonable measures to protect the confidentiality of the
        personal information and its transmission through the internet, and it shall not be held
        liable for disclosure of the confidential information when in accordance with this Privacy
        Policy or in terms of the agreements, if any, with the user/subscribers. To preserve the
        confidentiality of all information you provide to us, the Company maintains the privacy
        principles mentioned hereinafter:
      </p>
      <h3 className="text-2xl font-semibold mt-6 mb-4">1. Nature of Information</h3>
      <h4 className="text-xl font-semibold mt-4 mb-2">1.1. Personal Information</h4>
      <p className="mb-4">
        Personal Information is Information collected that can be used to uniquely identify or
        contact you. Personal Information for the purposes of this Privacy Policy shall include,
        but not be limited to:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Your address</li>
        <li>Your telephone number</li>
        <li>Your e-mail address or other contact information</li>
        <li>Your date of birth</li>
        <li>Your gender</li>
        <li>Your financial records</li>
        <li>Information regarding your transactions on the Website/App (including transaction history)</li>
        <li>
          Your financial information such as bank account information, credit card or debit card,
          or other payment instrument details
        </li>
        <li>Internet Protocol address</li>
        <li>
          Identification code of your communication device which you use to access the Website/App
        </li>
        <li>
          Any other Information that you provide during your registration process, if any, on the
          Website/App
        </li>
      </ul>
      <h4 className="text-xl font-semibold mt-4 mb-2">1.2. Non-Personal Information</h4>
      <p className="mb-4">
        Sanctum may also collect information other than Personal Information from users/subscribers
        through the Website/App when the user/subscriber visits and/or uses the Website/App. Such
        information may be stored in server logs. This Non-Personal Information would not assist
        Sanctum to identify you personally.
      </p>
      <p className="mb-4">
        We will automatically receive and collect certain anonymous information in standard usage
        logs through our Web server, including computer-identification information obtained from
        "cookies," sent to your browser from a:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>Web server cookie stored on your hard drive</li>
        <li>An IP address, assigned to the computer which you use</li>
        <li>The domain server through which you access our service</li>
        <li>The type of computer you're using</li>
        <li>The type of web browser you're using</li>
      </ul>
      <h3 className="text-2xl font-semibold mt-6 mb-4">2. Mode of Collection of Information</h3>
      <p className="mb-4">
        When you use the Sanctum Website and/or App, we collect and store your Information, which
        is provided by you from time to time. Our primary goal in doing so is to provide you a safe,
        efficient, smooth, and customized experience.
      </p>
      <p className="mb-4">
        We may automatically track certain information about you based upon your behavior on the
        Sanctum Website and/or App. We use this information to do internal research on our users'
        demographics, interests, and behavior to better understand, protect, and serve our users.
      </p>
      <h3 className="text-2xl font-semibold mt-6 mb-4">3. Use of Information</h3>
      <p className="mb-4">
        The Company undertakes not to disclose (includes selling, sharing, and renting) Information
        collected by the Company at any time to any third party without your consent except in
        accordance with this Privacy Policy. However, the Company also reserves the right to
        disclose Information in good faith:
      </p>
      <ul className="list-disc list-inside mb-4">
        <li>if required by law or any authority;</li>
        <li>
          to protect and defend the rights and interests of the Company, employees/agents of the
          Company, other users, or the general public;
        </li>
        <li>to enforce Terms of Use and other policies of the Company;</li>
        <li>to address concerns raised by a third party.</li>
      </ul>
      <p>
        For more details, please visit our full privacy policy at{" "}
        <a
          href="https://www.sanctumprop.com/legal-privacy"
          className="text-blue-700 underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          sanctumprop.com/legal-privacy
        </a>
      </p>
    </div>
  );
};



const RiskDisclosure = () => {
    return (
      <div className="risk-disclosure px-4 py-8">
      
        <p className="mb-4">
          Users are required to evaluate the following considerations, among others, carefully before
          making an investment in the opportunities appearing on this website. Prospective investors
          should give careful consideration to the following actual and potential risk factors in
          evaluating the merits and suitability of an investment in an opportunity appearing herein.
          The risks and facts set forth below are not exhaustive; additional risks and uncertainties
          not presently known, or deemed immaterial with respect to an investment in the opportunity
          may exist. Prospective investors should have the financial ability and willingness to
          accept the risks and lack of liquidity, which are characteristics of the investments
          described herein. There will be no public market for the units of the opportunity.
        </p>
        <p className="mb-4">
          Because of the uncertainties and subjective judgments inherent in selecting opportunities
          and the assumptions made; and because future events and circumstances cannot be predicted,
          there can be no assurance that the desired expected results of the opportunity will be
          achieved. The actual results may differ materially. In making an investment decision, users
          must rely on their own examination of the opportunity and the terms of the offering,
          including the merits and risks involved.
        </p>
        <h3 className="text-2xl font-semibold text-blue-900 mt-6 mb-4">Potential Risk Factors</h3>
        <ul className="list-disc list-inside space-y-4">
          <li>
            <strong>Data and Forecasts:</strong> Market data and certain industry forecasts used in
            forecasts for an opportunity are obtained from market research, publicly available
            information and industry publications. Industry publications generally state that the
            information they contain has been obtained from sources believed to be reliable, but
            that the accuracy and completeness of that information is not guaranteed.
          </li>
          <li>
            <strong>Forward-looking statements:</strong> Investment outcome forecasts are based on
            numerous assumptions, present and future business strategies, and the environment in
            which the opportunity will operate in the future. The actual outcomes may differ
            materially from those in the forward-looking statements.
          </li>
          <li>
            <strong>Real Estate Ownership in General:</strong> The investments we recommend will be
            subject to the risks generally incident to the ownership, operation, and development of
            real property. Market fluctuations and cycles may result in occasional or permanent
            reductions in the value of the investments.
          </li>
          <li>
            <strong>Leverage:</strong> The investments in the opportunities currently do not have any
            avenues for leverage.
          </li>
          <li>
            <strong>Long-term Investment:</strong> Each investment opportunity will set out a minimum
            lock-in period of anywhere between 3 months to 6 months. Additional periods of time may
            be required for the investments to reach maturity.
          </li>
          <li>
            <strong>Illiquidity of Investments:</strong> Purchases of the securities we recommend
            should be considered a long-term investment. Liquidity may not be achieved at the
            projected price at all times, and there is no public market available for the securities.
          </li>
          <li>
            <strong>Minority Investment:</strong> Investment in a particular opportunity will
            represent a minority stake that cannot exercise control or exert significant influence on
            the management of the opportunity.
          </li>
          <li>
            <strong>General Macroeconomic Conditions:</strong> Macroeconomic factors such as interest
            rates, inflation, and trade barriers may impact the opportunity’s success and liquidity.
          </li>
          <li>
            <strong>Changes in Indian Laws and Regulations:</strong> Legal and regulatory changes
            could occur, adversely affecting the value of the real property or the expenditure of the
            company.
          </li>
          <li>
            <strong>Reliance on Asset Manager:</strong> The asset manager provides support in
            accounting, tax, and other administrative services. Limitations on the liability of the
            asset manager and its affiliates are specified in agreements.
          </li>
          <li>
            <strong>Operational Risks:</strong> The asset manager’s operations depend on systems that
            may interface with third-party systems, leading to risks that could impact performance.
          </li>
          <li>
            <strong>Professional Advice:</strong> The company or asset manager urges prospective
            investors to consult their legal, tax, and financial advisers regarding the suitability
            of an investment.
          </li>
          <li>
            <strong>Natural or Man-Made Disasters:</strong> Disasters such as floods, pandemics, and
            terrorist acts could negatively affect the performance of the real estate market, thereby
            impacting the opportunity.
          </li>
        </ul>
        <p className="mt-6">
          <strong>Disclaimer:</strong> The foregoing risk factors do not purport to be a complete
          explanation of all of the risks involved in the opportunity. Potential investors should
          read this document and the opportunity documents in their entirety before determining the
          risk factors associated with subscribing to the opportunity.
        </p>
      </div>
    );
  };
  
  
  

const sections = {
  "Terms and Conditions": (
   <TermsAndConditions/>
  ),
  "Privacy Policy": (
   <PrivacyPolicy/>
  ),
  "Risk Disclosure": (
    <RiskDisclosure/>
  ),
};

const ContentSwitcher = () => {
  const [activeSection, setActiveSection] = useState("Privacy Policy");

  return (
    <div className="content-switcher px-6 py-10">
      {/* Navigation */}
      <div className="flex space-x-6 border-b border-gray-300 pb-2">
        {Object.keys(sections).map((heading) => (
          <button
            key={heading}
            onClick={() => setActiveSection(heading)}
            className={`text-lg font-semibold ${
              activeSection === heading
                ? "text-blue-900 border-b-2 border-yellow-500"
                : "text-gray-700"
            } hover:text-blue-700`}
          >
            {heading}
          </button>
        ))}
      </div>

      {/* Content */}
      <div className="mt-6">
        <h2 className="text-2xl font-bold text-blue-900">{activeSection}</h2>
        <div className="mt-4 text-gray-700 leading-7">
          {sections[activeSection]}
        </div>
      </div>
    </div>
  );
};

export default ContentSwitcher;
